services:
  connect-pg:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=connect
    volumes:
      - pgdata:/bitnami/postgresql

  connect-redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/bitnami/redis
    
  # frontend:
  #   container_name: frontend
  #   image: blackvsk/genia:front
  #   ports:
  #     - 80:80

  # MS:
  #   container_name: MS
  #   image: blackvsk/genia:MS
  #   env_file:
  #     - .env
  #   ports:
  #     - 3001:3000

volumes:
  pgdata:
  redisdata:
