version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: local_postgres
    environment:
      POSTGRES_USER: monta
      POSTGRES_PASSWORD: monta
      POSTGRES_DB: monta
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    
  frontend:
    container_name: frontend
    image: blackvsk/genia:front
    ports:
      - 80:80

  MS:
    container_name: MS
    image: blackvsk/genia:MS
    env_file:
      - .env
    ports:
      - 3001:3000

volumes:
  pgdata:
