apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back

    spec:
      containers:
      - name: back-container
        image: blackvsk/genia:back
        imagePullPolicy: Always

        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                  name: back-secret
                  key: DATABASE_URL
          
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                  name: back-secret
                  key: REDIS_URL

          - name: PORT
            valueFrom:
              secretKeyRef:
                  name: back-secret
                  key: PORT
          
          - name: MERCADOPAGO_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                  name: back-secret
                  key: MERCADOPAGO_ACCESS_TOKEN

          - name: GOOGLE_GENERATIVE_AI_API_KEY
            valueFrom:
              secretKeyRef:
                  name: back-secret
                  key: GOOGLE_GENERATIVE_AI_API_KEY
              
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                  name: back-secret
                  key: JWT_SECRET

          - name: CLOUD_NAME
            valueFrom:
              secretKeyRef:
                  name: back-secret
                  key: CLOUD_NAME

          - name: CLOUD_API_KEY
            valueFrom:
              secretKeyRef:
                  name: back-secret
                  key: CLOUD_API_KEY

          - name: CLOUD_API_SECRET
            valueFrom:
              secretKeyRef:
                  name: back-secret
                  key: CLOUD_API_SECRET

          - name: NODE_ENV
            valueFrom:
              secretKeyRef:
                  name: back-secret
                  key: NODE_ENV

          - name: API_MS_PIX
            valueFrom:
              secretKeyRef:
                  name: back-secret
                  key: API_MS_PIX

        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

        ports:
        - containerPort: 3002
---

apiVersion: v1
kind: Service
metadata:
  name: back-service

spec:
  selector:
    app: back

  type: LoadBalancer

  ports:
  - port: 3000
    targetPort: 3002

---

apiVersion: v1
kind: Secret
metadata:
  name: back-secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzLnJudWNhYW1leHRic2duYmZwcWZzOktHY3lsSVhIYmlTdm4xNVpAYXdzLTAtdXMtZWFzdC0yLnBvb2xlci5zdXBhYmFzZS5jb206NTQzMi9wb3N0Z3Jlcw==
  REDIS_URL: cmVkaXM6Ly9sb2NhbGhvc3Q6NjM3OQ==
  PORT: MzAwMg==
  MERCADOPAGO_ACCESS_TOKEN: QVBQX1VTUi02ODQ3ODE4ODE2NzQ1MjI3LTA1MjcxNy0xYjk4MzIxNmYyOGIzZjk1YTk5Y2QwYmJkZmQ0ODdmYy0yNzkxMzQ1MDc=
  GOOGLE_GENERATIVE_AI_API_KEY: QUl6YVN5RGg3OEVHYTE1SHhCaEJHSkgteldXYTNWTlU3ZFVQNmVB
  JWT_SECRET: ZGVmYXVsdC1zZWNyZXQtd2l0aC0zMi1jaGFycy0xMjM0NTY3ODkx
  CLOUD_NAME: ZGRla2RseHM0
  CLOUD_API_KEY: MTcyODI4MjYzNDk2OTcz
  CLOUD_API_SECRET: WnJBVXllaUZNS1QtdWtrcjVMam11OENMX0w4
  NODE_ENV: cHJvZA==
  API_MS_PIX: aHR0cDovL2EyYjc1NDE4NTdjMzA0YjYzYjE2ZDg3MmNjYmUzODMzLTIxMzMwNzc3NjYuc2EtZWFzdC0xLmVsYi5hbWF6b25hd3MuY29tOjMwMDEvYXBp